os:
  - linux
  - osx

osx_image:
  - xcode12.2

env:
  - SWIFT_VERSION=5.3

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
